/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as ConfirmRouteImport } from './routes/confirm'
import { Route as DesignRouteImport } from './routes/design'
import { Route as ForgotRouteImport } from './routes/forgot'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MfaRouteImport } from './routes/mfa'
import { Route as ResetRouteImport } from './routes/reset'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedSelectTenantRouteImport } from './routes/_authenticated/select-tenant'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as AuthenticatedTTenantIdRouteImport } from './routes/_authenticated/t.$tenantId'
import { Route as AuthenticatedTTenantIdIndexRouteImport } from './routes/_authenticated/t.$tenantId.index'
import { Route as AuthenticatedTTenantIdAuditRouteImport } from './routes/_authenticated/t.$tenantId.audit'
import { Route as AuthenticatedTTenantIdCashRouteImport } from './routes/_authenticated/t.$tenantId.cash'
import { Route as AuthenticatedTTenantIdPlansRouteImport } from './routes/_authenticated/t.$tenantId.plans'
import { Route as AuthenticatedTTenantIdTenantsRouteImport } from './routes/_authenticated/t.$tenantId.tenants'
import { Route as AuthenticatedTTenantIdSettingsUsersRouteImport } from './routes/_authenticated/t.$tenantId.settings.users'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmRoute = ConfirmRouteImport.update({
  id: '/confirm',
  path: '/confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignRoute = DesignRouteImport.update({
  id: '/design',
  path: '/design',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotRoute = ForgotRouteImport.update({
  id: '/forgot',
  path: '/forgot',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MfaRoute = MfaRouteImport.update({
  id: '/mfa',
  path: '/mfa',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetRoute = ResetRouteImport.update({
  id: '/reset',
  path: '/reset',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSelectTenantRoute =
  AuthenticatedSelectTenantRouteImport.update({
    id: '/select-tenant',
    path: '/select-tenant',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTTenantIdRoute = AuthenticatedTTenantIdRouteImport.update({
  id: '/t/$tenantId',
  path: '/t/$tenantId',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTTenantIdIndexRoute =
  AuthenticatedTTenantIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedTTenantIdRoute,
  } as any)
const AuthenticatedTTenantIdAuditRoute =
  AuthenticatedTTenantIdAuditRouteImport.update({
    id: '/audit',
    path: '/audit',
    getParentRoute: () => AuthenticatedTTenantIdRoute,
  } as any)
const AuthenticatedTTenantIdCashRoute =
  AuthenticatedTTenantIdCashRouteImport.update({
    id: '/cash',
    path: '/cash',
    getParentRoute: () => AuthenticatedTTenantIdRoute,
  } as any)
const AuthenticatedTTenantIdPlansRoute =
  AuthenticatedTTenantIdPlansRouteImport.update({
    id: '/plans',
    path: '/plans',
    getParentRoute: () => AuthenticatedTTenantIdRoute,
  } as any)
const AuthenticatedTTenantIdTenantsRoute =
  AuthenticatedTTenantIdTenantsRouteImport.update({
    id: '/tenants',
    path: '/tenants',
    getParentRoute: () => AuthenticatedTTenantIdRoute,
  } as any)
const AuthenticatedTTenantIdSettingsUsersRoute =
  AuthenticatedTTenantIdSettingsUsersRouteImport.update({
    id: '/settings/users',
    path: '/settings/users',
    getParentRoute: () => AuthenticatedTTenantIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/confirm': typeof ConfirmRoute
  '/design': typeof DesignRoute
  '/forgot': typeof ForgotRoute
  '/login': typeof LoginRoute
  '/mfa': typeof MfaRoute
  '/reset': typeof ResetRoute
  '/signup': typeof SignupRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/select-tenant': typeof AuthenticatedSelectTenantRoute
  '/invite/$token': typeof InviteTokenRoute
  '/t/$tenantId': typeof AuthenticatedTTenantIdRouteWithChildren
  '/t/$tenantId/audit': typeof AuthenticatedTTenantIdAuditRoute
  '/t/$tenantId/cash': typeof AuthenticatedTTenantIdCashRoute
  '/t/$tenantId/plans': typeof AuthenticatedTTenantIdPlansRoute
  '/t/$tenantId/tenants': typeof AuthenticatedTTenantIdTenantsRoute
  '/t/$tenantId/': typeof AuthenticatedTTenantIdIndexRoute
  '/t/$tenantId/settings/users': typeof AuthenticatedTTenantIdSettingsUsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/confirm': typeof ConfirmRoute
  '/design': typeof DesignRoute
  '/forgot': typeof ForgotRoute
  '/login': typeof LoginRoute
  '/mfa': typeof MfaRoute
  '/reset': typeof ResetRoute
  '/signup': typeof SignupRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/select-tenant': typeof AuthenticatedSelectTenantRoute
  '/invite/$token': typeof InviteTokenRoute
  '/t/$tenantId/audit': typeof AuthenticatedTTenantIdAuditRoute
  '/t/$tenantId/cash': typeof AuthenticatedTTenantIdCashRoute
  '/t/$tenantId/plans': typeof AuthenticatedTTenantIdPlansRoute
  '/t/$tenantId/tenants': typeof AuthenticatedTTenantIdTenantsRoute
  '/t/$tenantId': typeof AuthenticatedTTenantIdIndexRoute
  '/t/$tenantId/settings/users': typeof AuthenticatedTTenantIdSettingsUsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/confirm': typeof ConfirmRoute
  '/design': typeof DesignRoute
  '/forgot': typeof ForgotRoute
  '/login': typeof LoginRoute
  '/mfa': typeof MfaRoute
  '/reset': typeof ResetRoute
  '/signup': typeof SignupRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/select-tenant': typeof AuthenticatedSelectTenantRoute
  '/invite/$token': typeof InviteTokenRoute
  '/_authenticated/t/$tenantId': typeof AuthenticatedTTenantIdRouteWithChildren
  '/_authenticated/t/$tenantId/audit': typeof AuthenticatedTTenantIdAuditRoute
  '/_authenticated/t/$tenantId/cash': typeof AuthenticatedTTenantIdCashRoute
  '/_authenticated/t/$tenantId/plans': typeof AuthenticatedTTenantIdPlansRoute
  '/_authenticated/t/$tenantId/tenants': typeof AuthenticatedTTenantIdTenantsRoute
  '/_authenticated/t/$tenantId/': typeof AuthenticatedTTenantIdIndexRoute
  '/_authenticated/t/$tenantId/settings/users': typeof AuthenticatedTTenantIdSettingsUsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/confirm'
    | '/design'
    | '/forgot'
    | '/login'
    | '/mfa'
    | '/reset'
    | '/signup'
    | '/profile'
    | '/select-tenant'
    | '/invite/$token'
    | '/t/$tenantId'
    | '/t/$tenantId/audit'
    | '/t/$tenantId/cash'
    | '/t/$tenantId/plans'
    | '/t/$tenantId/tenants'
    | '/t/$tenantId/'
    | '/t/$tenantId/settings/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/confirm'
    | '/design'
    | '/forgot'
    | '/login'
    | '/mfa'
    | '/reset'
    | '/signup'
    | '/profile'
    | '/select-tenant'
    | '/invite/$token'
    | '/t/$tenantId/audit'
    | '/t/$tenantId/cash'
    | '/t/$tenantId/plans'
    | '/t/$tenantId/tenants'
    | '/t/$tenantId'
    | '/t/$tenantId/settings/users'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/confirm'
    | '/design'
    | '/forgot'
    | '/login'
    | '/mfa'
    | '/reset'
    | '/signup'
    | '/_authenticated/profile'
    | '/_authenticated/select-tenant'
    | '/invite/$token'
    | '/_authenticated/t/$tenantId'
    | '/_authenticated/t/$tenantId/audit'
    | '/_authenticated/t/$tenantId/cash'
    | '/_authenticated/t/$tenantId/plans'
    | '/_authenticated/t/$tenantId/tenants'
    | '/_authenticated/t/$tenantId/'
    | '/_authenticated/t/$tenantId/settings/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ConfirmRoute: typeof ConfirmRoute
  DesignRoute: typeof DesignRoute
  ForgotRoute: typeof ForgotRoute
  LoginRoute: typeof LoginRoute
  MfaRoute: typeof MfaRoute
  ResetRoute: typeof ResetRoute
  SignupRoute: typeof SignupRoute
  InviteTokenRoute: typeof InviteTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirm': {
      id: '/confirm'
      path: '/confirm'
      fullPath: '/confirm'
      preLoaderRoute: typeof ConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design': {
      id: '/design'
      path: '/design'
      fullPath: '/design'
      preLoaderRoute: typeof DesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot': {
      id: '/forgot'
      path: '/forgot'
      fullPath: '/forgot'
      preLoaderRoute: typeof ForgotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mfa': {
      id: '/mfa'
      path: '/mfa'
      fullPath: '/mfa'
      preLoaderRoute: typeof MfaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset': {
      id: '/reset'
      path: '/reset'
      fullPath: '/reset'
      preLoaderRoute: typeof ResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/select-tenant': {
      id: '/_authenticated/select-tenant'
      path: '/select-tenant'
      fullPath: '/select-tenant'
      preLoaderRoute: typeof AuthenticatedSelectTenantRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/t/$tenantId': {
      id: '/_authenticated/t/$tenantId'
      path: '/t/$tenantId'
      fullPath: '/t/$tenantId'
      preLoaderRoute: typeof AuthenticatedTTenantIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/t/$tenantId/': {
      id: '/_authenticated/t/$tenantId/'
      path: '/'
      fullPath: '/t/$tenantId/'
      preLoaderRoute: typeof AuthenticatedTTenantIdIndexRouteImport
      parentRoute: typeof AuthenticatedTTenantIdRoute
    }
    '/_authenticated/t/$tenantId/audit': {
      id: '/_authenticated/t/$tenantId/audit'
      path: '/audit'
      fullPath: '/t/$tenantId/audit'
      preLoaderRoute: typeof AuthenticatedTTenantIdAuditRouteImport
      parentRoute: typeof AuthenticatedTTenantIdRoute
    }
    '/_authenticated/t/$tenantId/cash': {
      id: '/_authenticated/t/$tenantId/cash'
      path: '/cash'
      fullPath: '/t/$tenantId/cash'
      preLoaderRoute: typeof AuthenticatedTTenantIdCashRouteImport
      parentRoute: typeof AuthenticatedTTenantIdRoute
    }
    '/_authenticated/t/$tenantId/plans': {
      id: '/_authenticated/t/$tenantId/plans'
      path: '/plans'
      fullPath: '/t/$tenantId/plans'
      preLoaderRoute: typeof AuthenticatedTTenantIdPlansRouteImport
      parentRoute: typeof AuthenticatedTTenantIdRoute
    }
    '/_authenticated/t/$tenantId/tenants': {
      id: '/_authenticated/t/$tenantId/tenants'
      path: '/tenants'
      fullPath: '/t/$tenantId/tenants'
      preLoaderRoute: typeof AuthenticatedTTenantIdTenantsRouteImport
      parentRoute: typeof AuthenticatedTTenantIdRoute
    }
    '/_authenticated/t/$tenantId/settings/users': {
      id: '/_authenticated/t/$tenantId/settings/users'
      path: '/settings/users'
      fullPath: '/t/$tenantId/settings/users'
      preLoaderRoute: typeof AuthenticatedTTenantIdSettingsUsersRouteImport
      parentRoute: typeof AuthenticatedTTenantIdRoute
    }
  }
}

interface AuthenticatedTTenantIdRouteChildren {
  AuthenticatedTTenantIdAuditRoute: typeof AuthenticatedTTenantIdAuditRoute
  AuthenticatedTTenantIdCashRoute: typeof AuthenticatedTTenantIdCashRoute
  AuthenticatedTTenantIdPlansRoute: typeof AuthenticatedTTenantIdPlansRoute
  AuthenticatedTTenantIdTenantsRoute: typeof AuthenticatedTTenantIdTenantsRoute
  AuthenticatedTTenantIdIndexRoute: typeof AuthenticatedTTenantIdIndexRoute
  AuthenticatedTTenantIdSettingsUsersRoute: typeof AuthenticatedTTenantIdSettingsUsersRoute
}

const AuthenticatedTTenantIdRouteChildren: AuthenticatedTTenantIdRouteChildren =
  {
    AuthenticatedTTenantIdAuditRoute: AuthenticatedTTenantIdAuditRoute,
    AuthenticatedTTenantIdCashRoute: AuthenticatedTTenantIdCashRoute,
    AuthenticatedTTenantIdPlansRoute: AuthenticatedTTenantIdPlansRoute,
    AuthenticatedTTenantIdTenantsRoute: AuthenticatedTTenantIdTenantsRoute,
    AuthenticatedTTenantIdIndexRoute: AuthenticatedTTenantIdIndexRoute,
    AuthenticatedTTenantIdSettingsUsersRoute:
      AuthenticatedTTenantIdSettingsUsersRoute,
  }

const AuthenticatedTTenantIdRouteWithChildren =
  AuthenticatedTTenantIdRoute._addFileChildren(
    AuthenticatedTTenantIdRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedSelectTenantRoute: typeof AuthenticatedSelectTenantRoute
  AuthenticatedTTenantIdRoute: typeof AuthenticatedTTenantIdRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedSelectTenantRoute: AuthenticatedSelectTenantRoute,
  AuthenticatedTTenantIdRoute: AuthenticatedTTenantIdRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ConfirmRoute: ConfirmRoute,
  DesignRoute: DesignRoute,
  ForgotRoute: ForgotRoute,
  LoginRoute: LoginRoute,
  MfaRoute: MfaRoute,
  ResetRoute: ResetRoute,
  SignupRoute: SignupRoute,
  InviteTokenRoute: InviteTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
